# Generated by Django 4.2.6 on 2023-10-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_clientes', '0002_cliente_razonsocial2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='razonsocial2',
        ),
    ]
