# Generated by Django 4.2.6 on 2023-10-07 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_clientes', '0003_remove_cliente_razonsocial2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')]),
        ),
    ]
