# Generated by Django 4.2.6 on 2023-10-07 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_clientes', '0004_alter_cliente_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{12}$')]),
        ),
    ]
